const { contactSyncDb } = require('./support/contactSyncDb')
describe('fila e HTTP da sincronização manual', () => {
  let db, queue, sync, controller, config
  beforeEach(() => {
    jest.resetModules()
    db = contactSyncDb()
    sync = jest.fn(async () => ({ ok: true, totalProcessados: 2, totalCriados: 2, totalFotosAtualizadas: 1 }))
    config = jest.fn(async () => ({ config: {} }))
    jest.doMock('../config/supabase', () => db)
    jest.doMock('../services/syncProgressivaService', () => ({ syncContactsFullProgressiva: sync }))
    jest.doMock('../services/configOperacionalService', () => ({ getConfig: async () => ({}), updateConfig: jest.fn(), isProcessamentoPausado: async () => true }))
    jest.doMock('../services/operationalAuditService', () => ({ registrarEvento: jest.fn(), TIPOS: {} }))
    jest.doMock('../services/operationalRateLimiter', () => ({ recordJobStart: jest.fn(), recordJobEnd: jest.fn() }))
    jest.doMock('../services/whatsappConfigService', () => ({ getEmpresaWhatsappConfig: config }))
    jest.doMock('../services/ultramsgIntegrationService', () => ({ getStatus: jest.fn() }))
    jest.doMock('../services/providers', () => ({ getProvider: jest.fn() }))
    queue = require('../services/queueManager')
    controller = require('../controllers/chat/integrationController')
  })
  function res() { return { status: jest.fn().mockReturnThis(), json: jest.fn().mockReturnThis() } }
  test('cliques simultâneos compartilham um único job', async () => {
    const results = await Promise.all([queue.enqueue(7, 'sync_contatos', { manual: true }), queue.enqueue(7, 'sync_contatos', { manual: true })])
    expect(results[0].job_id).toBe(results[1].job_id)
    expect(db.tables.jobs).toHaveLength(1)
  })
  test('clique enfileira somente a empresa do JWT; segundo clique retorna o mesmo job', async () => {
    const req = { user: { company_id: 7 }, body: { company_id: 8 } }
    const response = res()
    await controller.sincronizarContatosZapi(req, response)
    expect(response.status).toHaveBeenCalledWith(202)
    expect(db.tables.jobs).toHaveLength(1)
    expect(db.tables.jobs[0]).toMatchObject({ company_id: 7, payload: { manual: true, includePhotos: true } })
    const second = res()
    await controller.sincronizarContatosZapi(req, second)
    expect(second.json).toHaveBeenCalledWith(expect.objectContaining({ job_id: db.tables.jobs[0].id, running: true }))
    expect(db.tables.jobs).toHaveLength(1)
  })
  test('sem instância ou erro de enqueue não informa sucesso', async () => {
    config.mockResolvedValueOnce({ error: 'sem config' })
    let response = res()
    await controller.sincronizarContatosZapi({ user: { company_id: 7 } }, response)
    expect(response.status).toHaveBeenCalledWith(400)
    db.failures['jobs:insert'] = { message: 'write failed' }
    response = res()
    await controller.sincronizarContatosZapi({ user: { company_id: 7 } }, response)
    expect(response.status).toHaveBeenCalledWith(500)
    expect(db.tables.jobs).toHaveLength(0)
  })
  test('clique desbloqueia apenas o job antigo pendente da empresa pausada', async () => {
    db.tables.jobs.push({ id: 5, company_id: 7, tipo: 'sync_contatos', status: 'pending', payload: { reset: true } })
    await controller.sincronizarContatosZapi({ user: { company_id: 7 } }, res())
    expect(db.tables.jobs).toHaveLength(1)
    expect(db.tables.jobs[0].payload).toMatchObject({ manual: true, includePhotos: true })
    expect(await queue.getNextPendingJob()).toMatchObject({ id: 5, status: 'running' })
  })
  test('job manual funciona com empresa pausada e atrás de outro job pausado', async () => {
    db.tables.jobs.push({ id: 1, company_id: 8, tipo: 'sync_fotos', status: 'pending', criado_em: '2020' })
    await queue.enqueue(7, 'sync_contatos', { manual: true })
    const job = await queue.getNextPendingJob()
    expect(job).toMatchObject({ company_id: 7, status: 'running' })
    const emit = jest.fn(), io = { to: jest.fn(() => ({ emit })) }
    await queue.processJob(job, io)
    expect(db.tables.jobs.find((j) => j.id === job.id).status).toBe('completed')
    expect(emit).toHaveBeenCalledWith('zapi_sync_contatos', expect.objectContaining({ running: false, fotos_atualizadas: 1 }))
    expect(io.to).toHaveBeenCalledWith('empresa_7')
  })
  test('falha do serviço vira retry/dead_letter, nunca completed nem sucesso no socket', async () => {
    sync.mockResolvedValue({ ok: false, error: 'UltraMSG indisponível', totalCriados: 1 })
    const job = { id: 10, company_id: 7, tipo: 'sync_contatos', status: 'running', tentativas: 3, max_tentativas: 3 }
    db.tables.jobs.push(job)
    const emit = jest.fn()
    await queue.processJob({ ...job }, { to: () => ({ emit }) })
    expect(job).toMatchObject({ status: 'dead_letter', erro: 'UltraMSG indisponível' })
    expect(emit).toHaveBeenCalledWith('zapi_sync_contatos', expect.objectContaining({ ok: false, error: 'UltraMSG indisponível' }))
  })
  test('status é leitura: recupera progresso após F5 e não revela job de outra empresa', async () => {
    db.tables.jobs.push({ id: 10, company_id: 7, tipo: 'sync_contatos', status: 'running' })
    db.tables.checkpoints_sync.push({ company_id: 7, tipo: 'contact_sync', detalhes_json: { job_id: 10, totalAgendaValidos: 40, totalVerificados: 10 } })
    let response = res()
    await controller.statusSincronizacaoContatos({ user: { company_id: 7 }, query: { job_id: '10' } }, response)
    expect(response.json).toHaveBeenCalledWith(expect.objectContaining({ total_agenda: 40, verificados: 10, running: true }))
    response = res()
    await controller.statusSincronizacaoContatos({ user: { company_id: 8 }, query: { job_id: '10' } }, response)
    expect(response.json).toHaveBeenCalledWith({ ok: true, running: false, status: 'idle' })
    expect(db.calls.every((op) => op.action === 'select')).toBe(true)
  })
})

test('conectar/reconectar WhatsApp não importa agenda, mesmo com preferência antiga habilitada', async () => {
  jest.resetModules()
  const db = contactSyncDb({ empresas: [{ id: 7, zapi_auto_sync_contatos: true }] })
  const enqueue = jest.fn()
  jest.doMock('../config/supabase', () => db)
  jest.doMock('../services/queueManager', () => ({ enqueue, JOB_TIPOS: { SYNC_CONTATOS: 'sync_contatos' } }))
  jest.doMock('../services/whatsappInstanceService', () => ({
    getDefaultWhatsappInstance: async () => ({ instance: { id: 1, instance_id: '123', instance_token: 'local-test' } }),
    toEmpresaWhatsappConfig: (instance) => instance,
  }))
  jest.doMock('../services/whatsappConfigService', () => ({ fetchWithTimeout: async () => ({ ok: true, text: async () => JSON.stringify({ status: 'authenticated' }) }) }))
  jest.doMock('../services/ultramsgGroupsSyncService', () => ({ syncGroups: async () => ({}), syncFromChats: async () => ({}) }))
  jest.doMock('../services/providers', () => ({ getProvider: () => ({}) }))
  const { getStatus } = jest.requireActual('../services/ultramsgIntegrationService')
  expect(await getStatus(7)).toMatchObject({ connected: true })
  await new Promise(setImmediate)
  expect(await getStatus(7)).toMatchObject({ connected: true })
  await new Promise(setImmediate)
  expect(enqueue).not.toHaveBeenCalled()
  expect(db.tables.jobs).toHaveLength(0)
})
