-- Etapa 6: status `pronta`, campos de confirmação e histórico de revisões.
-- Seguro: DROP/ADD constraint de status + CREATE TABLE IF NOT EXISTS + ADD COLUMN.

-- =========================================================
-- 1. STATUS: adicionar `pronta` à constraint
-- =========================================================
ALTER TABLE public.disparo_campanhas
  DROP CONSTRAINT IF EXISTS disparo_campanhas_status_check;

ALTER TABLE public.disparo_campanhas
  ADD CONSTRAINT disparo_campanhas_status_check
  CHECK (status IN (
    'rascunho',
    'configurando',
    'pronta',
    'agendada',
    'em_execucao',
    'pausada',
    'concluida',
    'cancelada',
    'arquivada'
  ));

-- =========================================================
-- 2. CAMPOS DE CONFIRMAÇÃO NA CAMPANHA
-- =========================================================
ALTER TABLE public.disparo_campanhas
  ADD COLUMN IF NOT EXISTS versao_atual integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS config_hash text,
  ADD COLUMN IF NOT EXISTS confirmada_em timestamptz,
  ADD COLUMN IF NOT EXISTS confirmada_por integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS autorizacao_aceita_em timestamptz,
  ADD COLUMN IF NOT EXISTS autorizacao_texto text;

COMMENT ON COLUMN public.disparo_campanhas.versao_atual IS
  'Número da última revisão confirmada (0 = nunca confirmada).';
COMMENT ON COLUMN public.disparo_campanhas.config_hash IS
  'SHA-256 da configuração congelada na última confirmação (sem credenciais).';
COMMENT ON COLUMN public.disparo_campanhas.status IS
  'Inclui pronta (confirmada, aguardando início futuro) e agendada (com data/hora). Sem envio na Etapa 6.';

-- =========================================================
-- 3. HISTÓRICO DE REVISÕES / SNAPSHOTS DE AUDITORIA
-- =========================================================
CREATE TABLE IF NOT EXISTS public.disparo_campanha_revisoes (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id              integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  campanha_id             bigint  NOT NULL REFERENCES public.disparo_campanhas(id) ON DELETE CASCADE,

  versao                  integer NOT NULL CHECK (versao > 0),
  hash                    text NOT NULL,
  status                  text NOT NULL DEFAULT 'ativa'
                            CHECK (status IN ('ativa', 'invalidada')),

  -- Resumo auditável (sem dump de PII, sem tokens)
  resumo                  jsonb NOT NULL DEFAULT '{}',
  quantidades             jsonb NOT NULL DEFAULT '{}',
  checklist_resumo        jsonb NOT NULL DEFAULT '{}',
  avisos_aceitos          jsonb NOT NULL DEFAULT '[]',

  -- Declaração de autorização
  declaracao_texto        text NOT NULL,
  confirmado_por          integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  confirmado_em           timestamptz NOT NULL DEFAULT now(),
  confirmado_ip           text,

  -- Invalidação (voltar para edição)
  invalidada_em           timestamptz,
  invalidada_por          integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  motivo_invalidacao      text,

  criado_em               timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT disparo_revisoes_campanha_versao_unique UNIQUE (campanha_id, versao)
);

CREATE INDEX IF NOT EXISTS idx_disparo_revisoes_campanha
  ON public.disparo_campanha_revisoes (company_id, campanha_id, versao DESC);

CREATE INDEX IF NOT EXISTS idx_disparo_revisoes_status
  ON public.disparo_campanha_revisoes (campanha_id, status);

ALTER TABLE public.disparo_campanha_revisoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.disparo_campanha_revisoes FROM anon, authenticated;
GRANT ALL ON public.disparo_campanha_revisoes TO service_role;

COMMENT ON TABLE public.disparo_campanha_revisoes IS
  'Histórico imutável de confirmações da campanha (Etapa 6). Snapshots sem credenciais e sem dump completo de PII.';
COMMENT ON COLUMN public.disparo_campanha_revisoes.resumo IS
  'Referências e metadados: ids de instâncias/variações, limites, janelas, modo de início — sem tokens.';
