-- Módulo Disparo de Mensagens — fundação das tabelas (sem lógica de envio).
-- Campanhas, instâncias associadas e destinatários.

-- =========================================================
-- 1. CAMPANHAS
-- =========================================================
CREATE TABLE IF NOT EXISTS public.disparo_campanhas (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id      integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  nome            varchar(180) NOT NULL,
  descricao       text,
  status          text NOT NULL DEFAULT 'rascunho'
                    CHECK (status IN (
                      'rascunho','configurando','agendada',
                      'em_execucao','pausada','concluida','cancelada','arquivada'
                    )),
  criado_por      integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  criado_em       timestamptz NOT NULL DEFAULT now(),
  atualizado_em   timestamptz NOT NULL DEFAULT now(),
  arquivado_em    timestamptz
);

CREATE INDEX IF NOT EXISTS disparo_campanhas_company_status_idx
  ON public.disparo_campanhas (company_id, status);
CREATE INDEX IF NOT EXISTS disparo_campanhas_company_criado_idx
  ON public.disparo_campanhas (company_id, criado_em DESC);
CREATE INDEX IF NOT EXISTS disparo_campanhas_company_atualizado_idx
  ON public.disparo_campanhas (company_id, atualizado_em DESC);

ALTER TABLE public.disparo_campanhas ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.disparo_campanhas FROM anon, authenticated;
GRANT ALL ON public.disparo_campanhas TO service_role;

-- =========================================================
-- 2. INSTÂNCIAS DA CAMPANHA
-- =========================================================
CREATE TABLE IF NOT EXISTS public.disparo_campanha_instancias (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id          integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  campanha_id         bigint  NOT NULL REFERENCES public.disparo_campanhas(id) ON DELETE CASCADE,
  instancia_id        integer NOT NULL REFERENCES public.whatsapp_instances(id) ON DELETE CASCADE,
  distribuicao        text NOT NULL DEFAULT 'equilibrada'
                        CHECK (distribuicao IN ('manual','quantidade','percentual','equilibrada')),
  quantidade          integer CHECK (quantidade IS NULL OR quantidade > 0),
  percentual          numeric(5,2) CHECK (percentual IS NULL OR (percentual > 0 AND percentual <= 100)),
  ordem               integer NOT NULL DEFAULT 0,
  ativa               boolean NOT NULL DEFAULT true,
  criado_em           timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS disparo_campanha_instancias_campanha_idx
  ON public.disparo_campanha_instancias (company_id, campanha_id);
CREATE UNIQUE INDEX IF NOT EXISTS disparo_campanha_instancias_unique_idx
  ON public.disparo_campanha_instancias (campanha_id, instancia_id);

ALTER TABLE public.disparo_campanha_instancias ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.disparo_campanha_instancias FROM anon, authenticated;
GRANT ALL ON public.disparo_campanha_instancias TO service_role;

-- =========================================================
-- 3. DESTINATÁRIOS DA CAMPANHA
-- =========================================================
CREATE TABLE IF NOT EXISTS public.disparo_campanha_destinatarios (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id          integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  campanha_id         bigint  NOT NULL REFERENCES public.disparo_campanhas(id) ON DELETE CASCADE,
  -- Vínculo opcional com contato salvo no ZapERP
  cliente_id          integer REFERENCES public.clientes(id) ON DELETE SET NULL,
  nome                varchar(180),
  telefone_original   varchar(30) NOT NULL,
  telefone_normalizado varchar(20) NOT NULL,
  origem              text NOT NULL DEFAULT 'manual'
                        CHECK (origem IN ('contato_salvo','importacao_planilha','manual')),
  variaveis           jsonb,
  instancia_id        integer REFERENCES public.whatsapp_instances(id) ON DELETE SET NULL,
  status              text NOT NULL DEFAULT 'pendente'
                        CHECK (status IN (
                          'pendente','processando','enviado','entregue',
                          'lido','falhou','excluido'
                        )),
  motivo_falha        text,
  processado_em       timestamptz,
  enviado_em          timestamptz,
  criado_em           timestamptz NOT NULL DEFAULT now()
);

-- Impede duplicata de telefone normalizado na mesma campanha
CREATE UNIQUE INDEX IF NOT EXISTS disparo_destinatarios_telefone_unique_idx
  ON public.disparo_campanha_destinatarios (campanha_id, telefone_normalizado)
  WHERE status <> 'excluido';

CREATE INDEX IF NOT EXISTS disparo_destinatarios_campanha_status_idx
  ON public.disparo_campanha_destinatarios (company_id, campanha_id, status);
CREATE INDEX IF NOT EXISTS disparo_destinatarios_instancia_idx
  ON public.disparo_campanha_destinatarios (company_id, instancia_id)
  WHERE status = 'pendente';

ALTER TABLE public.disparo_campanha_destinatarios ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.disparo_campanha_destinatarios FROM anon, authenticated;
GRANT ALL ON public.disparo_campanha_destinatarios TO service_role;
