-- Comunidades (WhatsApp Communities via Whapi): fila persistente de adição/remoção/promoção
-- de participantes, com claim atômico (SKIP LOCKED), lease e advisory lock por instância.
-- Espelha o padrão do Disparo (20260822120000_disparo_fila_etapa7.sql), enxuto p/ 2 tabelas.
-- Comunidades/grupos/participantes/admins são lidos AO VIVO da Whapi — sem tabela-espelho.
-- Limite por instância fica em whatsapp_instances.metadata.comunidade_limites (jsonb) — sem tabela nova.

-- =========================================================
-- 1. OPERAÇÕES (cabeçalho do lote)
-- =========================================================
CREATE TABLE IF NOT EXISTS public.comunidade_operacoes (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id            integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  whatsapp_instance_id  integer NOT NULL REFERENCES public.whatsapp_instances(id) ON DELETE RESTRICT,
  comunidade_id         varchar(64) NOT NULL,          -- @g.us
  comunidade_nome       text,
  operacao              text NOT NULL DEFAULT 'add'
                          CHECK (operacao IN ('add','remove','promote','demote')),
  status                text NOT NULL DEFAULT 'em_execucao'
                          CHECK (status IN (
                            'em_execucao','pausada','concluida','concluida_com_erros','cancelada'
                          )),
  total                 integer NOT NULL DEFAULT 0,
  concluidos            integer NOT NULL DEFAULT 0,
  falhados              integer NOT NULL DEFAULT 0,
  ignorados             integer NOT NULL DEFAULT 0,
  pausa_motivo          text,
  criado_por            integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_comunidade_operacoes_company
  ON public.comunidade_operacoes (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comunidade_operacoes_status
  ON public.comunidade_operacoes (company_id, status)
  WHERE status IN ('em_execucao','pausada');

ALTER TABLE public.comunidade_operacoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.comunidade_operacoes FROM anon, authenticated;
GRANT ALL ON public.comunidade_operacoes TO service_role;

-- =========================================================
-- 2. FILA DE ITENS (um por participante)
-- =========================================================
CREATE TABLE IF NOT EXISTS public.comunidade_fila_itens (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operacao_id             uuid    NOT NULL REFERENCES public.comunidade_operacoes(id) ON DELETE CASCADE,
  company_id              integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  whatsapp_instance_id    integer NOT NULL REFERENCES public.whatsapp_instances(id) ON DELETE RESTRICT,
  comunidade_id           varchar(64) NOT NULL,         -- @g.us
  operacao                text NOT NULL DEFAULT 'add'
                            CHECK (operacao IN ('add','remove','promote','demote')),
  participante_jid        varchar(40) NOT NULL,         -- dígitos (Contact ID Whapi)

  status                  text NOT NULL DEFAULT 'pendente'
                            CHECK (status IN (
                              'pendente','reservada','enviando','concluida','falhou','ignorada','cancelada'
                            )),
  tentativas              integer NOT NULL DEFAULT 0,
  max_tentativas          integer NOT NULL DEFAULT 5,

  planejado_para          timestamptz,
  proxima_tentativa_em    timestamptz NOT NULL DEFAULT now(),
  chave_idempotencia      text NOT NULL,

  worker_id               text,
  lease_inicio            timestamptz,
  lease_ate               timestamptz,

  resultado               text
                            CHECK (resultado IS NULL OR resultado IN ('processed','failed')),
  erro_codigo             text,
  erro_mensagem           text,

  concluido_em            timestamptz,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT comunidade_fila_idempotencia_unique UNIQUE (chave_idempotencia)
);

CREATE INDEX IF NOT EXISTS idx_comunidade_fila_claim
  ON public.comunidade_fila_itens (status, proxima_tentativa_em, whatsapp_instance_id)
  WHERE status IN ('pendente','reservada');

CREATE INDEX IF NOT EXISTS idx_comunidade_fila_operacao
  ON public.comunidade_fila_itens (operacao_id, status);

CREATE INDEX IF NOT EXISTS idx_comunidade_fila_lease
  ON public.comunidade_fila_itens (lease_ate)
  WHERE status IN ('reservada','enviando');

ALTER TABLE public.comunidade_fila_itens ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.comunidade_fila_itens FROM anon, authenticated;
GRANT ALL ON public.comunidade_fila_itens TO service_role;

COMMENT ON TABLE public.comunidade_fila_itens IS
  'Fila persistente de participantes de Comunidade. Claim via RPC comunidade_claim_fila_itens (SKIP LOCKED).';
COMMENT ON COLUMN public.comunidade_fila_itens.chave_idempotencia IS
  'Formato: op:{operacao_id}:p:{participante_jid}';

-- =========================================================
-- 3. RPC: claim atômico com SKIP LOCKED (só de operações em_execucao)
-- =========================================================
CREATE OR REPLACE FUNCTION public.comunidade_claim_fila_itens(
  p_worker_id text,
  p_limit integer DEFAULT 3,
  p_lease_seconds integer DEFAULT 120,
  p_instancia_id integer DEFAULT NULL
)
RETURNS SETOF public.comunidade_fila_itens
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_limit integer := GREATEST(1, LEAST(COALESCE(p_limit, 3), 25));
  v_lease interval := make_interval(secs => GREATEST(30, LEAST(COALESCE(p_lease_seconds, 120), 900)));
BEGIN
  IF p_worker_id IS NULL OR length(trim(p_worker_id)) = 0 THEN
    RAISE EXCEPTION 'worker_id obrigatório';
  END IF;

  RETURN QUERY
  WITH candidatos AS (
    SELECT f.id
    FROM public.comunidade_fila_itens f
    INNER JOIN public.comunidade_operacoes o ON o.id = f.operacao_id
    WHERE f.status = 'pendente'
      AND f.proxima_tentativa_em <= now()
      AND o.status = 'em_execucao'
      AND (p_instancia_id IS NULL OR f.whatsapp_instance_id = p_instancia_id)
    ORDER BY f.proxima_tentativa_em ASC, f.id ASC
    FOR UPDATE OF f SKIP LOCKED
    LIMIT v_limit
  )
  UPDATE public.comunidade_fila_itens f
  SET
    status = 'reservada',
    worker_id = p_worker_id,
    lease_inicio = now(),
    lease_ate = now() + v_lease,
    updated_at = now()
  FROM candidatos c
  WHERE f.id = c.id
  RETURNING f.*;
END;
$$;

REVOKE ALL ON FUNCTION public.comunidade_claim_fila_itens(text, integer, integer, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.comunidade_claim_fila_itens(text, integer, integer, integer) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.comunidade_claim_fila_itens(text, integer, integer, integer) TO service_role;

-- Recupera leases expirados (reservada/enviando → pendente)
CREATE OR REPLACE FUNCTION public.comunidade_recuperar_leases(
  p_limit integer DEFAULT 100
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count integer;
BEGIN
  WITH upd AS (
    UPDATE public.comunidade_fila_itens
    SET
      status = 'pendente',
      worker_id = NULL,
      lease_inicio = NULL,
      lease_ate = NULL,
      updated_at = now(),
      proxima_tentativa_em = now()
    WHERE id IN (
      SELECT id FROM public.comunidade_fila_itens
      WHERE status IN ('reservada', 'enviando')
        AND lease_ate IS NOT NULL
        AND lease_ate < now()
      ORDER BY lease_ate ASC
      FOR UPDATE SKIP LOCKED
      LIMIT GREATEST(1, LEAST(COALESCE(p_limit, 100), 500))
    )
    RETURNING id
  )
  SELECT COUNT(*)::integer INTO v_count FROM upd;
  RETURN COALESCE(v_count, 0);
END;
$$;

REVOKE ALL ON FUNCTION public.comunidade_recuperar_leases(integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.comunidade_recuperar_leases(integer) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.comunidade_recuperar_leases(integer) TO service_role;

-- Advisory lock por instância (key namespace: comunidade_inst = 872015)
CREATE OR REPLACE FUNCTION public.comunidade_try_lock_instancia(p_instancia_id integer)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_instancia_id IS NULL OR p_instancia_id <= 0 THEN
    RETURN false;
  END IF;
  RETURN pg_try_advisory_lock(872015, p_instancia_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.comunidade_unlock_instancia(p_instancia_id integer)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_instancia_id IS NULL OR p_instancia_id <= 0 THEN
    RETURN false;
  END IF;
  RETURN pg_advisory_unlock(872015, p_instancia_id);
END;
$$;

REVOKE ALL ON FUNCTION public.comunidade_try_lock_instancia(integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.comunidade_unlock_instancia(integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.comunidade_try_lock_instancia(integer) FROM anon, authenticated;
REVOKE ALL ON FUNCTION public.comunidade_unlock_instancia(integer) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.comunidade_try_lock_instancia(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.comunidade_unlock_instancia(integer) TO service_role;
