-- Etapa 7: fila persistente, execuções, exclusões e claim atômico (SKIP LOCKED).
-- Sem Redis. Envio real permanece controlado por feature flags no app (default off).

-- =========================================================
-- 1. LISTA DE EXCLUSÃO (por empresa)
-- =========================================================
CREATE TABLE IF NOT EXISTS public.disparo_exclusoes (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id            integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  telefone_normalizado  varchar(20) NOT NULL,
  telefone_original     varchar(30),
  motivo                text,
  origem                text NOT NULL DEFAULT 'manual'
                          CHECK (origem IN ('manual','importacao','optout','sistema')),
  ativo                 boolean NOT NULL DEFAULT true,
  criado_por            integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  criado_em             timestamptz NOT NULL DEFAULT now(),
  removido_por          integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  removido_em           timestamptz,
  CONSTRAINT disparo_exclusoes_unique UNIQUE (company_id, telefone_normalizado)
);

CREATE INDEX IF NOT EXISTS idx_disparo_exclusoes_company_ativo
  ON public.disparo_exclusoes (company_id, ativo)
  WHERE ativo = true;

ALTER TABLE public.disparo_exclusoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.disparo_exclusoes FROM anon, authenticated;
GRANT ALL ON public.disparo_exclusoes TO service_role;

-- =========================================================
-- 2. EXECUÇÕES DA CAMPANHA
-- =========================================================
CREATE TABLE IF NOT EXISTS public.disparo_execucoes (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id            integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  campanha_id           bigint  NOT NULL REFERENCES public.disparo_campanhas(id) ON DELETE CASCADE,
  revisao_id            bigint  REFERENCES public.disparo_campanha_revisoes(id) ON DELETE SET NULL,
  versao                integer NOT NULL,
  config_hash           text NOT NULL,

  status                text NOT NULL DEFAULT 'aguardando'
                          CHECK (status IN (
                            'aguardando','em_execucao','pausada','concluida','cancelada','emergencia'
                          )),
  motivo_pausa          text,
  tipo_pausa            text
                          CHECK (tipo_pausa IS NULL OR tipo_pausa IN (
                            'manual','operacional','limite','horario','erro','desconexao','emergencia','data_limite'
                          )),

  iniciado_em           timestamptz,
  finalizado_em         timestamptz,
  iniciado_por          integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  pausado_por           integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  cancelado_por         integer REFERENCES public.usuarios(id) ON DELETE SET NULL,

  total_itens           integer NOT NULL DEFAULT 0,
  total_enviados        integer NOT NULL DEFAULT 0,
  total_entregues       integer NOT NULL DEFAULT 0,
  total_lidos           integer NOT NULL DEFAULT 0,
  total_falhas          integer NOT NULL DEFAULT 0,
  total_incertos        integer NOT NULL DEFAULT 0,
  total_ignorados       integer NOT NULL DEFAULT 0,
  total_cancelados      integer NOT NULL DEFAULT 0,

  dry_run               boolean NOT NULL DEFAULT true,
  criado_em             timestamptz NOT NULL DEFAULT now(),
  atualizado_em         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_disparo_execucoes_campanha
  ON public.disparo_execucoes (company_id, campanha_id, criado_em DESC);
CREATE INDEX IF NOT EXISTS idx_disparo_execucoes_status
  ON public.disparo_execucoes (company_id, status)
  WHERE status IN ('aguardando','em_execucao','pausada');

ALTER TABLE public.disparo_execucoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.disparo_execucoes FROM anon, authenticated;
GRANT ALL ON public.disparo_execucoes TO service_role;

-- =========================================================
-- 3. EVENTOS DE EXECUÇÃO
-- =========================================================
CREATE TABLE IF NOT EXISTS public.disparo_execucao_eventos (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id            integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  execucao_id           bigint  NOT NULL REFERENCES public.disparo_execucoes(id) ON DELETE CASCADE,
  campanha_id           bigint  NOT NULL REFERENCES public.disparo_campanhas(id) ON DELETE CASCADE,
  tipo                  text NOT NULL,
  payload               jsonb NOT NULL DEFAULT '{}',
  usuario_id            integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  criado_em             timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_disparo_exec_eventos_exec
  ON public.disparo_execucao_eventos (execucao_id, criado_em DESC);

ALTER TABLE public.disparo_execucao_eventos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.disparo_execucao_eventos FROM anon, authenticated;
GRANT ALL ON public.disparo_execucao_eventos TO service_role;

-- =========================================================
-- 4. HISTÓRICO DE PAUSAS
-- =========================================================
CREATE TABLE IF NOT EXISTS public.disparo_pausas (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id            integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  execucao_id           bigint  NOT NULL REFERENCES public.disparo_execucoes(id) ON DELETE CASCADE,
  campanha_id           bigint  NOT NULL REFERENCES public.disparo_campanhas(id) ON DELETE CASCADE,
  instancia_id          integer REFERENCES public.whatsapp_instances(id) ON DELETE SET NULL,
  tipo_pausa            text NOT NULL
                          CHECK (tipo_pausa IN (
                            'manual','operacional','limite','horario','erro','desconexao','emergencia','data_limite'
                          )),
  motivo                text,
  escopo                text NOT NULL DEFAULT 'campanha'
                          CHECK (escopo IN ('campanha','instancia')),
  iniciado_em           timestamptz NOT NULL DEFAULT now(),
  finalizado_em         timestamptz,
  iniciado_por          integer REFERENCES public.usuarios(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_disparo_pausas_exec
  ON public.disparo_pausas (execucao_id, iniciado_em DESC);

ALTER TABLE public.disparo_pausas ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.disparo_pausas FROM anon, authenticated;
GRANT ALL ON public.disparo_pausas TO service_role;

-- =========================================================
-- 5. FILA DE ITENS
-- =========================================================
CREATE TABLE IF NOT EXISTS public.disparo_fila_itens (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id              integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  campanha_id             bigint  NOT NULL REFERENCES public.disparo_campanhas(id) ON DELETE CASCADE,
  execucao_id             bigint  NOT NULL REFERENCES public.disparo_execucoes(id) ON DELETE CASCADE,
  revisao_id              bigint  REFERENCES public.disparo_campanha_revisoes(id) ON DELETE SET NULL,
  versao                  integer NOT NULL,
  destinatario_id         bigint  NOT NULL REFERENCES public.disparo_campanha_destinatarios(id) ON DELETE CASCADE,
  instancia_id            integer NOT NULL REFERENCES public.whatsapp_instances(id) ON DELETE RESTRICT,
  variacao_id             bigint  NOT NULL REFERENCES public.disparo_campanha_variacoes(id) ON DELETE RESTRICT,

  status                  text NOT NULL DEFAULT 'pendente'
                            CHECK (status IN (
                              'pendente','reservada','enviando','enviada','entregue','lida',
                              'falhou','incerta','ignorada','cancelada'
                            )),
  tentativas              integer NOT NULL DEFAULT 0,
  max_tentativas          integer NOT NULL DEFAULT 5,

  planejado_para          timestamptz,
  proxima_tentativa_em    timestamptz NOT NULL DEFAULT now(),
  chave_idempotencia      text NOT NULL,

  worker_id               text,
  lease_inicio            timestamptz,
  lease_ate               timestamptz,

  reference_id            text,
  provider_message_id     text,
  mensagem_id             bigint,
  conversa_id             integer,

  erro_codigo             text,
  erro_mensagem           text,
  erro_classificacao      text
                            CHECK (erro_classificacao IS NULL OR erro_classificacao IN ('temporario','permanente')),

  enviado_em              timestamptz,
  entregue_em             timestamptz,
  lido_em                 timestamptz,
  falhou_em               timestamptz,
  cancelado_em            timestamptz,

  criado_em               timestamptz NOT NULL DEFAULT now(),
  atualizado_em           timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT disparo_fila_idempotencia_unique UNIQUE (chave_idempotencia)
);

CREATE INDEX IF NOT EXISTS idx_disparo_fila_claim
  ON public.disparo_fila_itens (status, proxima_tentativa_em, instancia_id)
  WHERE status IN ('pendente','reservada');

CREATE INDEX IF NOT EXISTS idx_disparo_fila_execucao
  ON public.disparo_fila_itens (execucao_id, status);

CREATE INDEX IF NOT EXISTS idx_disparo_fila_campanha
  ON public.disparo_fila_itens (company_id, campanha_id, status);

CREATE INDEX IF NOT EXISTS idx_disparo_fila_lease
  ON public.disparo_fila_itens (lease_ate)
  WHERE status IN ('reservada','enviando');

CREATE INDEX IF NOT EXISTS idx_disparo_fila_reference
  ON public.disparo_fila_itens (reference_id)
  WHERE reference_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_disparo_fila_provider
  ON public.disparo_fila_itens (provider_message_id)
  WHERE provider_message_id IS NOT NULL;

ALTER TABLE public.disparo_fila_itens ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.disparo_fila_itens FROM anon, authenticated;
GRANT ALL ON public.disparo_fila_itens TO service_role;

COMMENT ON TABLE public.disparo_fila_itens IS
  'Fila persistente do Disparo (Etapa 7). Claim via RPC disparo_claim_fila_itens (SKIP LOCKED).';
COMMENT ON COLUMN public.disparo_fila_itens.chave_idempotencia IS
  'Formato: campanha:{id}:v{versao}:dest:{destinatario_id}';

-- =========================================================
-- 6. WORKER HEARTBEAT (saúde)
-- =========================================================
CREATE TABLE IF NOT EXISTS public.disparo_worker_heartbeat (
  worker_id             text PRIMARY KEY,
  hostname              text,
  pid                   integer,
  dry_run               boolean NOT NULL DEFAULT true,
  live_enabled          boolean NOT NULL DEFAULT false,
  ultima_atividade_em   timestamptz NOT NULL DEFAULT now(),
  iniciado_em           timestamptz NOT NULL DEFAULT now(),
  meta                  jsonb NOT NULL DEFAULT '{}'
);

ALTER TABLE public.disparo_worker_heartbeat ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.disparo_worker_heartbeat FROM anon, authenticated;
GRANT ALL ON public.disparo_worker_heartbeat TO service_role;

-- =========================================================
-- 7. RPC: claim atômico com SKIP LOCKED
-- =========================================================
CREATE OR REPLACE FUNCTION public.disparo_claim_fila_itens(
  p_worker_id text,
  p_limit integer DEFAULT 5,
  p_lease_seconds integer DEFAULT 120,
  p_instancia_id integer DEFAULT NULL
)
RETURNS SETOF public.disparo_fila_itens
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_limit integer := GREATEST(1, LEAST(COALESCE(p_limit, 5), 50));
  v_lease interval := make_interval(secs => GREATEST(30, LEAST(COALESCE(p_lease_seconds, 120), 900)));
BEGIN
  IF p_worker_id IS NULL OR length(trim(p_worker_id)) = 0 THEN
    RAISE EXCEPTION 'worker_id obrigatório';
  END IF;

  RETURN QUERY
  WITH candidatos AS (
    SELECT f.id
    FROM public.disparo_fila_itens f
    INNER JOIN public.disparo_execucoes e ON e.id = f.execucao_id
    WHERE f.status = 'pendente'
      AND f.proxima_tentativa_em <= now()
      AND e.status = 'em_execucao'
      AND (p_instancia_id IS NULL OR f.instancia_id = p_instancia_id)
    ORDER BY f.proxima_tentativa_em ASC, f.id ASC
    FOR UPDATE OF f SKIP LOCKED
    LIMIT v_limit
  )
  UPDATE public.disparo_fila_itens f
  SET
    status = 'reservada',
    worker_id = p_worker_id,
    lease_inicio = now(),
    lease_ate = now() + v_lease,
    atualizado_em = now()
  FROM candidatos c
  WHERE f.id = c.id
  RETURNING f.*;
END;
$$;

REVOKE ALL ON FUNCTION public.disparo_claim_fila_itens(text, integer, integer, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.disparo_claim_fila_itens(text, integer, integer, integer) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.disparo_claim_fila_itens(text, integer, integer, integer) TO service_role;

-- Recupera leases expirados (reservada/enviando → pendente)
CREATE OR REPLACE FUNCTION public.disparo_recuperar_leases_expirados(
  p_limit integer DEFAULT 100
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count integer;
BEGIN
  WITH upd AS (
    UPDATE public.disparo_fila_itens
    SET
      status = 'pendente',
      worker_id = NULL,
      lease_inicio = NULL,
      lease_ate = NULL,
      atualizado_em = now(),
      proxima_tentativa_em = now()
    WHERE id IN (
      SELECT id FROM public.disparo_fila_itens
      WHERE status IN ('reservada', 'enviando')
        AND lease_ate IS NOT NULL
        AND lease_ate < now()
      ORDER BY lease_ate ASC
      FOR UPDATE SKIP LOCKED
      LIMIT GREATEST(1, LEAST(COALESCE(p_limit, 100), 500))
    )
    RETURNING id
  )
  SELECT COUNT(*)::integer INTO v_count FROM upd;
  RETURN COALESCE(v_count, 0);
END;
$$;

REVOKE ALL ON FUNCTION public.disparo_recuperar_leases_expirados(integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.disparo_recuperar_leases_expirados(integer) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.disparo_recuperar_leases_expirados(integer) TO service_role;

-- Advisory lock por instância (key namespace: disparo_inst:{id})
CREATE OR REPLACE FUNCTION public.disparo_try_lock_instancia(p_instancia_id integer)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_instancia_id IS NULL OR p_instancia_id <= 0 THEN
    RETURN false;
  END IF;
  RETURN pg_try_advisory_lock(872014, p_instancia_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.disparo_unlock_instancia(p_instancia_id integer)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_instancia_id IS NULL OR p_instancia_id <= 0 THEN
    RETURN false;
  END IF;
  RETURN pg_advisory_unlock(872014, p_instancia_id);
END;
$$;

REVOKE ALL ON FUNCTION public.disparo_try_lock_instancia(integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.disparo_unlock_instancia(integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.disparo_try_lock_instancia(integer) FROM anon, authenticated;
REVOKE ALL ON FUNCTION public.disparo_unlock_instancia(integer) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.disparo_try_lock_instancia(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.disparo_unlock_instancia(integer) TO service_role;
