-- HelpDesk multi-tenant: chamados, mensagens e histórico de transferências.
CREATE TABLE IF NOT EXISTS public.helpdesk_tickets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  titulo varchar(180) NOT NULL,
  descricao text NOT NULL,
  prioridade text NOT NULL DEFAULT 'normal' CHECK (prioridade IN ('baixa', 'normal', 'alta', 'urgente')),
  status text NOT NULL DEFAULT 'aberto' CHECK (status IN ('aberto', 'em_atendimento', 'aguardando', 'resolvido', 'fechado')),
  cliente_id integer REFERENCES public.clientes(id) ON DELETE SET NULL,
  departamento_id integer REFERENCES public.departamentos(id) ON DELETE SET NULL,
  responsavel_id integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  criado_por integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  atualizado_por integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  atribuido_em timestamptz,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.helpdesk_mensagens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  ticket_id bigint NOT NULL REFERENCES public.helpdesk_tickets(id) ON DELETE CASCADE,
  autor_usuario_id integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  mensagem text NOT NULL,
  interna boolean NOT NULL DEFAULT false,
  criado_em timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.helpdesk_transferencias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  ticket_id bigint NOT NULL REFERENCES public.helpdesk_tickets(id) ON DELETE CASCADE,
  de_departamento_id integer REFERENCES public.departamentos(id) ON DELETE SET NULL,
  para_departamento_id integer REFERENCES public.departamentos(id) ON DELETE SET NULL,
  de_responsavel_id integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  para_responsavel_id integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  transferido_por integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  motivo text,
  criado_em timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS helpdesk_tickets_company_updated_idx
  ON public.helpdesk_tickets (company_id, atualizado_em DESC);
CREATE INDEX IF NOT EXISTS helpdesk_tickets_company_status_idx
  ON public.helpdesk_tickets (company_id, status);
CREATE INDEX IF NOT EXISTS helpdesk_mensagens_ticket_idx
  ON public.helpdesk_mensagens (company_id, ticket_id, criado_em);
CREATE INDEX IF NOT EXISTS helpdesk_transferencias_ticket_idx
  ON public.helpdesk_transferencias (company_id, ticket_id, criado_em);

ALTER TABLE public.helpdesk_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.helpdesk_mensagens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.helpdesk_transferencias ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.helpdesk_tickets FROM anon, authenticated;
REVOKE ALL ON public.helpdesk_mensagens FROM anon, authenticated;
REVOKE ALL ON public.helpdesk_transferencias FROM anon, authenticated;
GRANT ALL ON public.helpdesk_tickets TO service_role;
GRANT ALL ON public.helpdesk_mensagens TO service_role;
GRANT ALL ON public.helpdesk_transferencias TO service_role;
