-- Etapa 4: variações de mensagem para o módulo Disparo.
-- Seguro: apenas ADD TABLE + ADD COLUMN IF NOT EXISTS — não altera dados anteriores.

-- ── Tabela principal: variações de mensagem ────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.disparo_campanha_variacoes (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id            integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  campanha_id           bigint  NOT NULL REFERENCES public.disparo_campanhas(id) ON DELETE CASCADE,

  -- Identificação
  nome                  text NOT NULL DEFAULT 'Variação A',
  tipo_mensagem         text NOT NULL DEFAULT 'texto'
                          CHECK (tipo_mensagem IN ('texto','imagem','video','audio','documento')),

  -- Conteúdo
  texto                 text,           -- corpo da mensagem ou legenda
  legenda               text,           -- legenda separada do texto principal (para mídias)

  -- Mídia (armazenada no R2 ou disco, nunca base64 no banco)
  midia_storage_key     text,           -- chave no R2 (ex.: media/disparo/1/42/3/uuid.mp4)
  midia_url_disco       text,           -- caminho relativo no disco quando não há R2
  midia_nome_original   text,
  midia_mime            text,
  midia_tamanho         bigint,

  -- Distribuição
  ordem                 integer NOT NULL DEFAULT 0,
  peso                  numeric(5,2) NOT NULL DEFAULT 100 CHECK (peso > 0),
  percentual            numeric(5,2) CHECK (percentual IS NULL OR (percentual > 0 AND percentual <= 100)),
  ativa                 boolean NOT NULL DEFAULT true,

  -- Rastreamento
  criado_por            integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  criado_em             timestamptz NOT NULL DEFAULT now(),
  atualizado_em         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_disparo_variacoes_campanha
  ON public.disparo_campanha_variacoes (campanha_id, company_id);

CREATE INDEX IF NOT EXISTS idx_disparo_variacoes_ordem
  ON public.disparo_campanha_variacoes (campanha_id, ordem);

COMMENT ON TABLE  public.disparo_campanha_variacoes IS
  'Variações de mensagem por campanha. Cada variação é uma mensagem completa (texto + opcional mídia).';
COMMENT ON COLUMN public.disparo_campanha_variacoes.midia_storage_key IS
  'Chave no Cloudflare R2 (começa com "media/disparo/"). Nulo quando em disco.';
COMMENT ON COLUMN public.disparo_campanha_variacoes.texto IS
  'Corpo da mensagem para tipo=texto, ou legenda para tipos com mídia.';

-- ── Novos campos na campanha: modo e estado das variações ─────────────────────
ALTER TABLE public.disparo_campanhas
  ADD COLUMN IF NOT EXISTS variacao_modo text
    CHECK (variacao_modo IS NULL OR variacao_modo IN ('unica','equilibrada','percentual','manual')),
  ADD COLUMN IF NOT EXISTS variacao_confirmada  boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS variacao_revisao     boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS variacao_padrao_valores jsonb NOT NULL DEFAULT '{}';

COMMENT ON COLUMN public.disparo_campanhas.variacao_modo IS
  'Modo de distribuição das variações: unica | equilibrada | percentual | manual';
COMMENT ON COLUMN public.disparo_campanhas.variacao_confirmada IS
  'True quando a distribuição de variações foi confirmada pelo administrador.';
COMMENT ON COLUMN public.disparo_campanhas.variacao_revisao IS
  'True quando destinatários/variações mudaram após confirmação — exige revisão.';
COMMENT ON COLUMN public.disparo_campanhas.variacao_padrao_valores IS
  'Valores padrão por variável (ex.: {"nome":"cliente","cidade":""}). Guardados na campanha.';

-- ── variacao_id em destinatários ──────────────────────────────────────────────
ALTER TABLE public.disparo_campanha_destinatarios
  ADD COLUMN IF NOT EXISTS variacao_id bigint
    REFERENCES public.disparo_campanha_variacoes(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_disparo_destinatarios_variacao
  ON public.disparo_campanha_destinatarios (campanha_id, variacao_id);

COMMENT ON COLUMN public.disparo_campanha_destinatarios.variacao_id IS
  'Variação de mensagem atribuída a este destinatário (null = ainda não distribuída).';
