const express = require('express')
const router = express.Router()
const auth = require('../middleware/auth')
const adminOnly = require('../middleware/adminOnly')
const supervisorOrAdmin = require('../middleware/supervisorOrAdmin')
const { destructiveLimiter } = require('../middleware/rateLimit')
const dashboardController = require('../controllers/dashboardController')

// Dashboard/métricas: supervisor e admin (atendente não acessa)
router.get('/overview', auth, supervisorOrAdmin, dashboardController.overview)
router.get('/metrics', auth, supervisorOrAdmin, dashboardController.metrics)
router.get('/metrics-avancadas', auth, supervisorOrAdmin, dashboardController.metricsAvancadas)
// Resumo do CRM Avançado (integração externa) — bloco lazy do painel
router.get('/crm-resumo', auth, supervisorOrAdmin, dashboardController.crmResumo)
router.get('/departamentos', auth, dashboardController.listarDepartamentos)
router.post('/departamentos', auth, adminOnly, dashboardController.criarDepartamento)
router.get('/departamentos/:id/grupos', auth, supervisorOrAdmin, dashboardController.listarGruposDepartamento)
router.put('/departamentos/:id/grupos', auth, supervisorOrAdmin, dashboardController.atualizarGruposDepartamento)
router.put('/departamentos/:id', auth, adminOnly, dashboardController.atualizarDepartamento)
router.delete('/departamentos/:id', auth, adminOnly, destructiveLimiter, dashboardController.excluirDepartamento)
router.get('/respostas-salvas', auth, dashboardController.listarRespostasSalvas)
router.post('/respostas-salvas', auth, dashboardController.criarRespostaSalva)
router.put('/respostas-salvas/:id', auth, dashboardController.atualizarRespostaSalva)
router.delete('/respostas-salvas/:id', auth, destructiveLimiter, dashboardController.excluirRespostaSalva)
router.get('/relatorios/conversas', auth, supervisorOrAdmin, dashboardController.relatorioConversas)
router.get('/relatorios/mensagens', auth, supervisorOrAdmin, dashboardController.relatorioMensagens)
router.get('/relatorios/export', auth, supervisorOrAdmin, dashboardController.exportRelatorio)
router.get('/sla/config', auth, supervisorOrAdmin, dashboardController.getSlaConfig)
router.put('/sla/config', auth, adminOnly, dashboardController.setSlaConfig)
router.get('/sla/alertas', auth, supervisorOrAdmin, dashboardController.getSlaAlertas)
router.get('/sla/resumo', auth, supervisorOrAdmin, dashboardController.slaResumo)
router.get('/sla/diaria', auth, supervisorOrAdmin, dashboardController.slaDiaria)
router.get('/sla/export', auth, supervisorOrAdmin, dashboardController.exportSla)
router.get('/sla/validacao/:conversa_id', auth, supervisorOrAdmin, dashboardController.slaValidacao)

module.exports = router
