const express = require('express')
const router = express.Router()
const auth = require('../middleware/auth')
const adminOnly = require('../middleware/adminOnly')
const supervisorOrAdmin = require('../middleware/supervisorOrAdmin')
const dashboardController = require('../controllers/dashboardController')

// Dashboard/métricas: supervisor e admin (atendente não acessa)
router.get('/overview', auth, supervisorOrAdmin, dashboardController.overview)
router.get('/metrics', auth, supervisorOrAdmin, dashboardController.metrics)
router.get('/metrics-avancadas', auth, supervisorOrAdmin, dashboardController.metricsAvancadas)
router.get('/departamentos', auth, dashboardController.listarDepartamentos)
router.post('/departamentos', auth, adminOnly, dashboardController.criarDepartamento)
router.put('/departamentos/:id', auth, adminOnly, dashboardController.atualizarDepartamento)
router.delete('/departamentos/:id', auth, adminOnly, dashboardController.excluirDepartamento)
router.get('/respostas-salvas', auth, supervisorOrAdmin, dashboardController.listarRespostasSalvas)
router.post('/respostas-salvas', auth, supervisorOrAdmin, dashboardController.criarRespostaSalva)
router.put('/respostas-salvas/:id', auth, supervisorOrAdmin, dashboardController.atualizarRespostaSalva)
router.delete('/respostas-salvas/:id', auth, supervisorOrAdmin, dashboardController.excluirRespostaSalva)
router.get('/relatorios/conversas', auth, supervisorOrAdmin, dashboardController.relatorioConversas)
router.get('/relatorios/mensagens', auth, supervisorOrAdmin, dashboardController.relatorioMensagens)
router.get('/relatorios/export', auth, supervisorOrAdmin, dashboardController.exportRelatorio)
router.get('/sla/config', auth, supervisorOrAdmin, dashboardController.getSlaConfig)
router.put('/sla/config', auth, adminOnly, dashboardController.setSlaConfig)
router.get('/sla/alertas', auth, supervisorOrAdmin, dashboardController.getSlaAlertas)

module.exports = router
