BEGIN;

CREATE TABLE IF NOT EXISTS public.helpdesk_notificacoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  usuario_id integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  ticket_id bigint NOT NULL REFERENCES public.helpdesk_tickets(id) ON DELETE CASCADE,
  tipo varchar(40) NOT NULL CHECK (tipo IN ('ticket_created', 'message_created', 'ticket_transferred')),
  titulo varchar(180) NOT NULL,
  mensagem varchar(500),
  lida boolean NOT NULL DEFAULT false,
  criado_em timestamptz NOT NULL DEFAULT now(),
  lida_em timestamptz
);

CREATE INDEX IF NOT EXISTS helpdesk_notificacoes_usuario_nao_lida_idx
  ON public.helpdesk_notificacoes (company_id, usuario_id, lida, criado_em DESC);

CREATE INDEX IF NOT EXISTS helpdesk_notificacoes_ticket_idx
  ON public.helpdesk_notificacoes (company_id, usuario_id, ticket_id);

-- Usado ao assumir, transferir ou resolver um chamado para encerrar, em lote,
-- as notificações pendentes de todos os destinatários daquele ticket.
CREATE INDEX IF NOT EXISTS helpdesk_notificacoes_ticket_nao_lida_idx
  ON public.helpdesk_notificacoes (company_id, ticket_id, usuario_id, tipo)
  WHERE lida = false;

ALTER TABLE public.helpdesk_notificacoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.helpdesk_notificacoes FROM anon, authenticated;
GRANT ALL ON public.helpdesk_notificacoes TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.helpdesk_notificacoes_id_seq TO service_role;

COMMIT;

SELECT
  table_name,
  column_name,
  data_type,
  column_default,
  is_nullable
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'helpdesk_notificacoes'
ORDER BY ordinal_position;
