CREATE TABLE IF NOT EXISTS public.conversa_atendentes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  conversa_id integer NOT NULL REFERENCES public.conversas(id) ON DELETE CASCADE,
  usuario_id integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  adicionado_por integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamp with time zone NOT NULL DEFAULT now(),
  atualizado_em timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS conversa_atendentes_active_unique
  ON public.conversa_atendentes (company_id, conversa_id, usuario_id)
  WHERE ativo = true;

CREATE INDEX IF NOT EXISTS idx_conversa_atendentes_usuario_active
  ON public.conversa_atendentes (company_id, usuario_id, conversa_id)
  WHERE ativo = true;

CREATE INDEX IF NOT EXISTS idx_conversa_atendentes_conversa_active
  ON public.conversa_atendentes (company_id, conversa_id, usuario_id)
  WHERE ativo = true;
