-- Etapa 5: limites, intervalos, lotes, janelas, fuso, agendamento e pausas.
-- Seguro: CREATE TABLE IF NOT EXISTS + ADD COLUMN IF NOT EXISTS.

-- =========================================================
-- 1. CONFIGURAÇÃO GLOBAL DE LIMITES DA CAMPANHA
-- =========================================================
CREATE TABLE IF NOT EXISTS public.disparo_campanha_limites (
  id                              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id                      integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  campanha_id                     bigint  NOT NULL REFERENCES public.disparo_campanhas(id) ON DELETE CASCADE,

  -- Perfil sugerido (apenas sugestão editável)
  perfil                          text NOT NULL DEFAULT 'moderado'
                                    CHECK (perfil IN ('conservador','moderado','personalizado')),

  -- Limites de volume
  limite_total                    integer CHECK (limite_total IS NULL OR limite_total > 0),
  limite_por_hora                 integer NOT NULL DEFAULT 60
                                    CHECK (limite_por_hora > 0 AND limite_por_hora <= 1000),
  limite_por_dia                  integer NOT NULL DEFAULT 500
                                    CHECK (limite_por_dia > 0 AND limite_por_dia <= 20000),

  -- Intervalos entre mensagens (segundos)
  intervalo_min_sec               integer NOT NULL DEFAULT 8
                                    CHECK (intervalo_min_sec >= 1 AND intervalo_min_sec <= 3600),
  intervalo_max_sec               integer NOT NULL DEFAULT 20
                                    CHECK (intervalo_max_sec >= 1 AND intervalo_max_sec <= 7200),

  -- Lotes e pausas entre lotes (segundos)
  lote_tamanho                    integer NOT NULL DEFAULT 20
                                    CHECK (lote_tamanho >= 1 AND lote_tamanho <= 500),
  pausa_lote_min_sec              integer NOT NULL DEFAULT 60
                                    CHECK (pausa_lote_min_sec >= 0 AND pausa_lote_min_sec <= 86400),
  pausa_lote_max_sec              integer NOT NULL DEFAULT 180
                                    CHECK (pausa_lote_max_sec >= 0 AND pausa_lote_max_sec <= 86400),

  -- Fuso e agendamento
  fuso_horario                    text NOT NULL DEFAULT 'America/Sao_Paulo',
  inicio_modo                     text NOT NULL DEFAULT 'imediato'
                                    CHECK (inicio_modo IN ('imediato','agendado')),
  agendado_para                   timestamptz,
  data_limite                     timestamptz,

  -- Pausas automáticas (regras salvas; processamento futuro)
  pausa_auto_desconexao           boolean NOT NULL DEFAULT true,
  pausa_auto_erros_consecutivos   integer NOT NULL DEFAULT 5
                                    CHECK (pausa_auto_erros_consecutivos >= 1 AND pausa_auto_erros_consecutivos <= 100),
  pausa_auto_taxa_falha_pct       numeric(5,2) NOT NULL DEFAULT 25
                                    CHECK (pausa_auto_taxa_falha_pct > 0 AND pausa_auto_taxa_falha_pct <= 100),

  -- Confirmação / revisão
  confirmada                      boolean NOT NULL DEFAULT false,
  revisao                         boolean NOT NULL DEFAULT false,
  configurado_por                 integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  criado_em                       timestamptz NOT NULL DEFAULT now(),
  atualizado_em                   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT disparo_limites_intervalo_ok CHECK (intervalo_min_sec <= intervalo_max_sec),
  CONSTRAINT disparo_limites_pausa_ok CHECK (pausa_lote_min_sec <= pausa_lote_max_sec),
  CONSTRAINT disparo_limites_agendamento_ok CHECK (
    (inicio_modo = 'imediato' AND agendado_para IS NULL)
    OR (inicio_modo = 'agendado')
  ),
  CONSTRAINT disparo_limites_campanha_unique UNIQUE (campanha_id)
);

CREATE INDEX IF NOT EXISTS idx_disparo_limites_company
  ON public.disparo_campanha_limites (company_id, campanha_id);

ALTER TABLE public.disparo_campanha_limites ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.disparo_campanha_limites FROM anon, authenticated;
GRANT ALL ON public.disparo_campanha_limites TO service_role;

COMMENT ON TABLE public.disparo_campanha_limites IS
  'Configuração global de limites, intervalos, lotes, fuso e agendamento da campanha (Etapa 5). Sem envio real.';
COMMENT ON COLUMN public.disparo_campanha_limites.limite_por_hora IS
  'Janela móvel de 60 minutos (regra operacional; fila futura respeita este valor).';
COMMENT ON COLUMN public.disparo_campanha_limites.limite_por_dia IS
  'Limite diário no fuso_horario da campanha.';

-- =========================================================
-- 2. LIMITES ESPECÍFICOS POR INSTÂNCIA (override opcional)
-- =========================================================
CREATE TABLE IF NOT EXISTS public.disparo_campanha_instancia_limites (
  id                              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id                      integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  campanha_id                     bigint  NOT NULL REFERENCES public.disparo_campanhas(id) ON DELETE CASCADE,
  instancia_id                    integer NOT NULL REFERENCES public.whatsapp_instances(id) ON DELETE CASCADE,

  -- false = herda global; true = usa campos abaixo
  herdar_global                   boolean NOT NULL DEFAULT true,

  limite_por_hora                 integer CHECK (limite_por_hora IS NULL OR (limite_por_hora > 0 AND limite_por_hora <= 1000)),
  limite_por_dia                  integer CHECK (limite_por_dia IS NULL OR (limite_por_dia > 0 AND limite_por_dia <= 20000)),
  intervalo_min_sec               integer CHECK (intervalo_min_sec IS NULL OR (intervalo_min_sec >= 1 AND intervalo_min_sec <= 3600)),
  intervalo_max_sec               integer CHECK (intervalo_max_sec IS NULL OR (intervalo_max_sec >= 1 AND intervalo_max_sec <= 7200)),
  lote_tamanho                    integer CHECK (lote_tamanho IS NULL OR (lote_tamanho >= 1 AND lote_tamanho <= 500)),
  pausa_lote_min_sec              integer CHECK (pausa_lote_min_sec IS NULL OR (pausa_lote_min_sec >= 0 AND pausa_lote_min_sec <= 86400)),
  pausa_lote_max_sec              integer CHECK (pausa_lote_max_sec IS NULL OR (pausa_lote_max_sec >= 0 AND pausa_lote_max_sec <= 86400)),
  -- true = usa janelas próprias em disparo_campanha_janelas com instancia_id preenchido
  janelas_proprias                boolean NOT NULL DEFAULT false,

  criado_em                       timestamptz NOT NULL DEFAULT now(),
  atualizado_em                   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT disparo_inst_limites_intervalo_ok CHECK (
    intervalo_min_sec IS NULL OR intervalo_max_sec IS NULL OR intervalo_min_sec <= intervalo_max_sec
  ),
  CONSTRAINT disparo_inst_limites_pausa_ok CHECK (
    pausa_lote_min_sec IS NULL OR pausa_lote_max_sec IS NULL OR pausa_lote_min_sec <= pausa_lote_max_sec
  ),
  CONSTRAINT disparo_inst_limites_unique UNIQUE (campanha_id, instancia_id)
);

CREATE INDEX IF NOT EXISTS idx_disparo_inst_limites_campanha
  ON public.disparo_campanha_instancia_limites (company_id, campanha_id);

ALTER TABLE public.disparo_campanha_instancia_limites ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.disparo_campanha_instancia_limites FROM anon, authenticated;
GRANT ALL ON public.disparo_campanha_instancia_limites TO service_role;

COMMENT ON TABLE public.disparo_campanha_instancia_limites IS
  'Overrides de limites por instância. herdar_global=true usa a configuração da campanha.';

-- =========================================================
-- 3. JANELAS DE HORÁRIO (globais ou por instância)
-- =========================================================
-- dia_semana: 0=domingo … 6=sábado (mesmo padrão de Date.getDay() / luxon weekday%7)
CREATE TABLE IF NOT EXISTS public.disparo_campanha_janelas (
  id                              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id                      integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  campanha_id                     bigint  NOT NULL REFERENCES public.disparo_campanhas(id) ON DELETE CASCADE,
  -- NULL = janela global da campanha; preenchido = janela exclusiva da instância
  instancia_id                    integer REFERENCES public.whatsapp_instances(id) ON DELETE CASCADE,

  dia_semana                      smallint NOT NULL CHECK (dia_semana >= 0 AND dia_semana <= 6),
  hora_inicio                     time NOT NULL,
  hora_fim                        time NOT NULL,
  ativo                           boolean NOT NULL DEFAULT true,

  criado_em                       timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT disparo_janela_horario_ok CHECK (hora_inicio < hora_fim)
);

CREATE INDEX IF NOT EXISTS idx_disparo_janelas_campanha
  ON public.disparo_campanha_janelas (company_id, campanha_id, dia_semana);

CREATE INDEX IF NOT EXISTS idx_disparo_janelas_instancia
  ON public.disparo_campanha_janelas (campanha_id, instancia_id)
  WHERE instancia_id IS NOT NULL;

ALTER TABLE public.disparo_campanha_janelas ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.disparo_campanha_janelas FROM anon, authenticated;
GRANT ALL ON public.disparo_campanha_janelas TO service_role;

COMMENT ON TABLE public.disparo_campanha_janelas IS
  'Janelas de envio por dia da semana. instancia_id NULL = global; preenchido = override da instância.';
COMMENT ON COLUMN public.disparo_campanha_janelas.dia_semana IS
  '0=domingo, 1=segunda, …, 6=sábado.';

-- =========================================================
-- 4. FLAGS DE REVISÃO NA CAMPANHA (Etapa 5)
-- =========================================================
ALTER TABLE public.disparo_campanhas
  ADD COLUMN IF NOT EXISTS limites_confirmados boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS limites_revisao     boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.disparo_campanhas.limites_confirmados IS
  'True quando a Etapa 5 (limites/horários) foi confirmada pelo administrador.';
COMMENT ON COLUMN public.disparo_campanhas.limites_revisao IS
  'True quando destinatários/instâncias/variações/limites mudaram após confirmação — exige revisão.';
