-- Etapa 8: opt-out, respostas inbound, reconciliação manual e config por empresa.
-- Sem envio automático — flags do app permanecem off por default.

-- =========================================================
-- 1. CONFIG DE OPT-OUT POR EMPRESA
-- =========================================================
CREATE TABLE IF NOT EXISTS public.disparo_empresa_config (
  company_id                    integer PRIMARY KEY REFERENCES public.empresas(id) ON DELETE CASCADE,
  palavras_optout               text[] NOT NULL DEFAULT '{SAIR,PARAR,CANCELAR,REMOVER,STOP}',
  mensagem_confirmacao_optout   text,
  reativacao_exige_explicito    boolean NOT NULL DEFAULT true,
  enviar_confirmacao_optout     boolean NOT NULL DEFAULT true,
  atualizado_em                 timestamptz NOT NULL DEFAULT now(),
  atualizado_por                integer REFERENCES public.usuarios(id) ON DELETE SET NULL
);

ALTER TABLE public.disparo_empresa_config ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.disparo_empresa_config FROM anon, authenticated;
GRANT ALL ON public.disparo_empresa_config TO service_role;

-- =========================================================
-- 2. FILA: colunas de resposta / opt-out + status ampliado
-- =========================================================
ALTER TABLE public.disparo_fila_itens
  ADD COLUMN IF NOT EXISTS respondida_em timestamptz,
  ADD COLUMN IF NOT EXISTS optout_em timestamptz,
  ADD COLUMN IF NOT EXISTS resposta_mensagem_id bigint,
  ADD COLUMN IF NOT EXISTS resposta_conversa_id integer;

ALTER TABLE public.disparo_fila_itens
  DROP CONSTRAINT IF EXISTS disparo_fila_itens_status_check;

ALTER TABLE public.disparo_fila_itens
  ADD CONSTRAINT disparo_fila_itens_status_check
  CHECK (status IN (
    'pendente','reservada','enviando','enviada','entregue','lida',
    'respondida','optout',
    'falhou','incerta','ignorada','cancelada'
  ));

CREATE INDEX IF NOT EXISTS idx_disparo_fila_respondida
  ON public.disparo_fila_itens (company_id, status, respondida_em DESC)
  WHERE status = 'respondida';

CREATE INDEX IF NOT EXISTS idx_disparo_fila_optout_em
  ON public.disparo_fila_itens (company_id, optout_em DESC)
  WHERE optout_em IS NOT NULL;

-- =========================================================
-- 3. RESPOSTAS VINCULADAS A DISPAROS
-- =========================================================
CREATE TABLE IF NOT EXISTS public.disparo_respostas (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id            integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  campanha_id           bigint  NOT NULL REFERENCES public.disparo_campanhas(id) ON DELETE CASCADE,
  execucao_id           bigint  NOT NULL REFERENCES public.disparo_execucoes(id) ON DELETE CASCADE,
  fila_item_id          bigint  NOT NULL REFERENCES public.disparo_fila_itens(id) ON DELETE CASCADE,
  destinatario_id       bigint  NOT NULL REFERENCES public.disparo_campanha_destinatarios(id) ON DELETE CASCADE,
  instancia_id          integer REFERENCES public.whatsapp_instances(id) ON DELETE SET NULL,
  mensagem_entrada_id   bigint  NOT NULL,
  mensagem_disparo_id   bigint,
  conversa_id           integer,
  telefone_normalizado  varchar(20) NOT NULL,
  criado_em             timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT disparo_respostas_mensagem_entrada_unique UNIQUE (company_id, mensagem_entrada_id)
);

CREATE INDEX IF NOT EXISTS idx_disparo_respostas_company
  ON public.disparo_respostas (company_id, criado_em DESC);
CREATE INDEX IF NOT EXISTS idx_disparo_respostas_campanha
  ON public.disparo_respostas (company_id, campanha_id, criado_em DESC);
CREATE INDEX IF NOT EXISTS idx_disparo_respostas_fila_item
  ON public.disparo_respostas (fila_item_id);
CREATE INDEX IF NOT EXISTS idx_disparo_respostas_telefone
  ON public.disparo_respostas (company_id, telefone_normalizado);

ALTER TABLE public.disparo_respostas ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.disparo_respostas FROM anon, authenticated;
GRANT ALL ON public.disparo_respostas TO service_role;

-- =========================================================
-- 4. EVENTOS DE OPT-OUT / REATIVAÇÃO
-- =========================================================
CREATE TABLE IF NOT EXISTS public.disparo_optout_eventos (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id            integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  telefone_normalizado  varchar(20) NOT NULL,
  palavra               text,
  exclusao_id           bigint  REFERENCES public.disparo_exclusoes(id) ON DELETE SET NULL,
  campanha_id           bigint  REFERENCES public.disparo_campanhas(id) ON DELETE SET NULL,
  execucao_id           bigint  REFERENCES public.disparo_execucoes(id) ON DELETE SET NULL,
  fila_item_id          bigint  REFERENCES public.disparo_fila_itens(id) ON DELETE SET NULL,
  mensagem_id           bigint,
  conversa_id           integer,
  tipo                  text NOT NULL CHECK (tipo IN ('optout', 'reativacao')),
  motivo                text,
  usuario_id            integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  criado_em             timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_disparo_optout_eventos_company
  ON public.disparo_optout_eventos (company_id, criado_em DESC);
CREATE INDEX IF NOT EXISTS idx_disparo_optout_eventos_telefone
  ON public.disparo_optout_eventos (company_id, telefone_normalizado, criado_em DESC);
CREATE INDEX IF NOT EXISTS idx_disparo_optout_eventos_fila
  ON public.disparo_optout_eventos (fila_item_id)
  WHERE fila_item_id IS NOT NULL;

ALTER TABLE public.disparo_optout_eventos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.disparo_optout_eventos FROM anon, authenticated;
GRANT ALL ON public.disparo_optout_eventos TO service_role;

-- =========================================================
-- 5. DECISÕES DE RECONCILIAÇÃO MANUAL (itens incertos)
-- =========================================================
CREATE TABLE IF NOT EXISTS public.disparo_reconciliacao_decisoes (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id            integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  fila_item_id          bigint  NOT NULL REFERENCES public.disparo_fila_itens(id) ON DELETE CASCADE,
  execucao_id           bigint  NOT NULL REFERENCES public.disparo_execucoes(id) ON DELETE CASCADE,
  decisao               text NOT NULL CHECK (decisao IN ('enviada', 'falhou', 'reatentar', 'manter_incerta')),
  justificativa         text NOT NULL,
  evidencias            jsonb NOT NULL DEFAULT '{}',
  usuario_id            integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  criado_em             timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_disparo_reconciliacao_company
  ON public.disparo_reconciliacao_decisoes (company_id, criado_em DESC);
CREATE INDEX IF NOT EXISTS idx_disparo_reconciliacao_fila
  ON public.disparo_reconciliacao_decisoes (fila_item_id, criado_em DESC);

ALTER TABLE public.disparo_reconciliacao_decisoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.disparo_reconciliacao_decisoes FROM anon, authenticated;
GRANT ALL ON public.disparo_reconciliacao_decisoes TO service_role;

COMMENT ON TABLE public.disparo_empresa_config IS
  'Configuração de opt-out por empresa (Etapa 8 Disparo).';
COMMENT ON TABLE public.disparo_respostas IS
  'Respostas inbound vinculadas a itens da fila de disparo.';
COMMENT ON TABLE public.disparo_optout_eventos IS
  'Auditoria de opt-out e reativações de telefones no Disparo.';
COMMENT ON TABLE public.disparo_reconciliacao_decisoes IS
  'Decisões manuais sobre itens incertos na fila de disparo.';
